### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by iliaoke** [Uotan-Dev/UotanToolBox#1]
1.希望添加关闭avb校验命令fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
2.添加功能搜索
3.添加解包payload.bin功能
4.如果在技术层面上可以的话,希望可以适配更多的底层深度刷机的功能。尽大可能的平替掉sp flash和高通官方的刷机工具(这俩工具全是英文，用起来太难受了。)

**Comment by mujianwu** [comment]
第一个已有相似功能，为禁用vbmeta（刷入一个空的vbmeta.img），搜索功能不太好实现，其余的可能会在未来加入。
