### ISSUE TITLE
维酷工具包 小bug

### ISSUE THREAD

**Issue by FFFomalhaut** [Uotan-Dev/UotanToolBox#2]
使用维酷刷机工具包时发现一个bug，在用9008刷机时，如果电脑上没有装高通9008的驱动，程序会卡住。
翻了一下bat里的代码发现，程序找到待刷设备，是靠在设备管理器里搜索“9008”。如果找不到就循环回去再找一次。没有驱动时设备管理器中显示`QHSUSB_BULK`而不是`QUALCOMM 9008`，程序找不到设备，就跑起了死循环。

**Comment by mujianwu** [comment]
维酷刷机工具是内置的其他作者的工具，该工具目前已停止维护。
